# environment: {}
packages:
  - name: generate-images
    # shared: false
    # environment: {}
    # parameters: {}
    # annotations: {}
    functions:
      - name: dall-e
        environment:
          OPENAI_API_KEY: "${OPENAI_API_KEY}"
          OPENAI_ORG: "${OPENAI_ORG}"
        # parameters:
        #   teamName: ''
        #   primaryColor: ''
        #   secondaryColor: ''
        #   userId: ''
        # annotations: {}
        # binary: false
        # main: "main"
        runtime: nodejs:18
        web: true
        # webSecure: false
        limits:
          # 2 minutes (2min allows for retries; see OpenAI API timeout)
          timeout: 120000
