packages:
  - name: generate-images
    functions:
      - name: dall-e
        environment:
          OPENAI_API_KEY: "${OPENAI_API_KEY}"
          OPENAI_ORG: "${OPENAI_ORG}"
        # parameters:
        #   teamName: ''
        #   primaryColor: ''
        #   secondaryColor: ''
        #   userId: ''
        # main: "main"
        runtime: nodejs:18
        web: true
        limits:
          # 2 minutes (2min allows for retries; see OpenAI API timeout)
          timeout: 120000
