alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
- rule: DEPLOYMENT_LIVE
domains:
- domain: lineup.app.xericode.net
  type: PRIMARY
  zone: app.xericode.net
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: web
    match:
      path:
        prefix: /
name: lineup-app
region: nyc
static_sites:
- build_command: npm run generate
  environment_slug: node-js
  envs:
  - key: NITRO_PRESET
    scope: BUILD_TIME
    value: digital-ocean
  - key: NUXT_APP_BASE_URL
    scope: BUILD_TIME
    value: '/'
  error_document: 404.html
  github:
    branch: main
    deploy_on_push: true
    repo: krazkidd/lineup
  name: web
  output_dir: .output/public
  source_dir: /
